# This file will be joined with docker-compose.app.yml from dcape
# See https://github.com/dopos/dcape

services:
  # This service will extend code from dcape
  app:
    volumes:
      - ./dnsdist.conf:/etc/dnsdist/dnsdist.conf
    ports:
      - ${LISTEN}:53/udp
      - ${LISTEN}:53/tcp
    labels:
      - traefik.http.services.${APP_TAG}.loadbalancer.server.port=80
